package com.guardianconnect.util

class Constants {

    companion object {
        const val GRD_CONFIG_STRING = "GRD_CONFIG_STRING"
        const val GRD_TRANSPORT_PROTOCOL = "TRANSPORT_PROTOCOL"
        const val GRD_WIREGUARD = "wireguard"
        const val GRD_UNKNOWN = "unknown"
        const val GRD_WIREGUARD_PRETTY = "Wireguard"
        const val GRD_UNKNOWN_PRETTY = "Unknown"
        const val GRD_SUBSCRIBER_CREDENTIAL = "GRD_SUBSCRIBER_CREDENTIAL"
        const val GRD_CONNECT_SUBSCRIBER = "GRD_CONNECT_SUBSCRIBER"
        const val GRD_CONNECT_SUBSCRIBER_SECRET = "GRD_CONNECT_SUBSCRIBER_SECRET"
        const val GRD_CONNECT_SUBSCRIBER_EMAIL = "GRD_CONNECT_SUBSCRIBER_EMAIL"
        const val GRD_CONNECT_DEVICE = "GRD_CONNECT_DEVICE"
        const val GRD_CREDENTIAL_LIST = "GRD_CREDENTIAL_LIST"
        const val GRD_MAIN = "main"
        const val GRD_PERSISTENT_LOG = "kGRDPersistentLog"
        const val GRD_PERSISTENT_LOG_ENABLED = "kGRDPersistentLogEnabled"
        const val GRD_Main_Credential_WG_Public_Key = "GRD-Main-Credential-WG-Public-Key"
        const val GRD_Main_Credential_WG_Private_Key = "GRD-Main-Credential-WG-Private-Key"
        const val GRD_Preferred_Region = "GRD_Preferred_Region"
        const val GRD_PREFERRED_REGION_NAME_PRETTY = "GRD_PREFERRED_REGION_NAME_PRETTY"
        const val GRD_REGIONS_LIST_FROM_SHARED_PREFS = "GRD_REGIONS_LIST_FROM_SHARED_PREFS"
        const val GRD_AUTOMATIC_REGION = "Automatic"
        const val GRD_PE_TOKEN = "GRD_PE_TOKEN"
        const val GRD_DEVICE_ID = "GRD_DEVICE_ID"
        const val GRD_API_AUTH_TOKEN = "GRD_API_AUTH_TOKEN"
        const val GRD_BLOCKLIST_BITMASK_STATE = "BITMASK_STATE"
        const val GRD_BLOCKLIST_BLOCK_NONE = "block-none"
        const val GRD_BLOCKLIST_BLOCK_ADS = "block-ads"
        const val GRD_BLOCKLIST_BLOCK_PHISHING = "block-phishing"
        const val API_ERROR = "Cannot make API requests!"
        const val GRD_PE_TOKEN_CONNECT_API_ENV = "GRD_PE_TOKEN_CONNECT_API_ENV"
        const val GRD_PE_TOKEN_EXPIRATION_DATE = "GRD_PE_TOKEN_EXPIRATION_DATE"
        const val GRD_CONNECT_USER_PREFERRED_DNS_SERVERS = "GRD_CONNECT_USER_PREFERRED_DNS_SERVERS"
        const val kGRDErrGuardianAccountNotSetup = "Guardian account setup not yet completed!"
        const val kGRDConnectAPIHostname = "connect-api.guardianapp.com"
        const val kGRDPreferredRegionPrecision = "kGRDPreferredRegionPrecision"
        const val kGRDRegionPrecisionDefault = "default"
        const val kGRDRegionPrecisionCity = "city"
        const val kGRDRegionPrecisionCountry = "city-by-country"
        const val kGRDAppExceptionsPackageNames = "kGRDAppExceptionsPackageNames"
        const val kGRDExcludeLANTraffic = "kGRDExcludeLANTraffic"
    }
}